In [1]:
# Install required library
!pip install -q kagglehub

In [3]:
# Import KaggleHub
import kagglehub

# Download the dataset
dataset_path = kagglehub.dataset_download("andrewmvd/trip-advisor-hotel-reviews")

print("Dataset downloaded successfully!")
print(dataset_path)

Downloading to /root/.cache/kagglehub/datasets/andrewmvd/trip-advisor-hotel-reviews/2.archive...

100%|██████████| 5.14M/5.14M [00:00<00:00, 145MB/s]

Extracting files...

Dataset downloaded successfully!
/root/.cache/kagglehub/datasets/andrewmvd/trip-advisor-hotel-reviews/versions/2

In [4]:
import pandas as pd
import os

In [5]:
# Check the downloaded files
print(os.listdir(dataset_path))

['tripadvisor_hotel_reviews.csv']

In [6]:
reviews = pd.read_csv(dataset_path + "/tripadvisor_hotel_reviews.csv")

reviews.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [7]:
# Display basic information
reviews.info()

# Check for missing values
reviews.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20491 entries, 0 to 20490
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  20491 non-null  object
 1   Rating  20491 non-null  int64
dtypes: int64(1), object(1)
memory usage: 320.3+ KB

Review    0
Rating    0
dtype: int64

In [8]:
# Convert ratings into sentiments

def find_sentiment(rating):
    if rating >= 4:
        return "Positive"
    elif rating <= 2:
        return "Negative"
    else:
        return "Neutral"

reviews["Sentiment"] = reviews["Rating"].apply(find_sentiment)

reviews.head()

                                              Review  Rating Sentiment
0  nice hotel expensive parking got good deal sta...       4  Positive
1  ok nothing special charge diamond member hilto...       2  Negative
2  nice rooms not 4* experience hotel monaco seat...       3   Neutral
3  unique, great stay, wonderful time hotel monac...       5  Positive
4  great stay great stay, went seahawk game aweso...       5  Positive

In [9]:
# Select review text
x = reviews["Review"]

# Select sentiment labels
y = reviews["Sentiment"]

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english")

x = vectorizer.fit_transform(x)

In [11]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [12]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(x_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [13]:
prediction = model.predict(x_test)

In [14]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, prediction)

print("Accuracy :", round(accuracy * 100, 2), "%")

Accuracy : 74.38 %

In [15]:
from sklearn.metrics import classification_report

print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

    Negative       0.88      0.01      0.02       625
     Neutral       0.00      0.00      0.00       432
    Positive       0.74      1.00      0.85      3042

    accuracy                           0.74      4099
   macro avg       0.54      0.34      0.29      4099
weighted avg       0.69      0.74      0.64      4099

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [16]:
my_review = [
    "The room was very clean and the staff were friendly."
]

review_vector = vectorizer.transform(my_review)

result = model.predict(review_vector)

print("Predicted Sentiment :", result[0])

Predicted Sentiment : Positive

In [17]:
my_review = [
    "The room was dirty and the service was terrible."
]

review_vector = vectorizer.transform(my_review)

result = model.predict(review_vector)

print("Predicted Sentiment :", result[0])

Predicted Sentiment : Negative